[tox]
envlist = py39, py310, py311, py312
skipsdist = True

[testenv]
deps =
    pytest
    pytest-asyncio
    requests
install_command = pip install {opts} {packages}
commands =
    pytest {posargs:-v --tb=short}

[testenv:bandit]
description = Run Bandit security linter
skip_install = true
deps =
    bandit
commands =
    bandit -r . --exclude ./.tox,./.git,./venv,./.venv,./build,./dist,./tests
